version: '3.7'

services:
  example-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    networks:
      - default_net
    ports:
      - 3308:3306

  example-api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: bash -c "bash ./wait-for-it.sh db:3306 -q -- diesel setup && cargo watch -x run"
    networks:
      - default_net
    env_file:
      - .env
    depends_on:
      - example-db

networks:
  default_net:
    name: default_net
    driver: bridge
volumes:
  db_data:
